### ISSUE TITLE
Figure out how to progamatically extract Twitter Data "At Scale"

### ISSUE THREAD

**Issue by VincentLa14** [sfbrigade/nltweets#1]
The issue is that calling the Twitter API for many rows, there's "Rate Limiting". So we need to figure out a way around that.

**Comment by steven4354** [comment]
https://github.com/bear/python-twitter/tree/master/twitter

**Comment by frhino** [comment]
Following @steven4354 's link, this specifically: https://github.com/bear/python-twitter/wiki/Rate-Limited-API---How-to-deal-with.

**Comment by frhino** [comment]
This tutorial has an easy to follow code snippet for programmatic extraction within rate limits: https://medium.com/agatha-codes/0-to-280-getting-twitter-timeline-data-for-your-awesome-nlp-project-ff41b941ed6

**Comment by frhino** [comment]
@nathanhc did a great job adding endpoints to the twitter pull in [PR 52](https://github.com/sfbrigade/nltweets/pull/52), closing a bunch of issues for those. Let's be sure to target that code in our main folder, so moving . Also creating a new issue for moving that code into the main/code path and renaming to represent the main trunk for that process now.

**Comment by frhino** [comment]
Closing this issue as we're now looking at a weekly chron job until and unless we acquire elevated creds.
