### ISSUE TITLE
Verify "credentials" folder readme is correct information

### ISSUE THREAD

**Issue by frhino** [sfbrigade/nltweets#13]
I'm not 100% positive [this info](https://github.com/sfbrigade/nltweets/blob/master/main/0_data/credentials/readme.md) is completely safe. If you know this area, please confirm, fix if necessary, and close this issue.

**Comment by frhino** [comment]
Also, would that notebook need to specify the full file path for the creds file if stored in the credentials folder in the data folder?

**Comment by pahdo** [comment]
@nathanhc closed this Issue with https://github.com/sfbrigade/nltweets/pull/60
