### ISSUE TITLE
Dedupe and Combine Labelled Twitter Data

### ISSUE THREAD

**Issue by nhilton92** [sfbrigade/nltweets#23]
- Dedupe posts for labelling from 
https://docs.google.com/spreadsheets/d/1duD-RUOTLNu9zW4aXqfgmow62pOcKUuUitxqeVRkbPs/edit#gid=0
and 
https://docs.google.com/spreadsheets/d/12mTqmgyiCDanTiPFrNdjj96UDZuQNCcnJdzdhOXeZn0/edit#gid=0

- Combine the tweets into one document

- Make sure not to delete any labels already applied to tweets

**Comment by frhino** [comment]
How about combine Label Tweets and Tweet2, then dedupe

**Comment by frhino** [comment]
@edenradovich  Looks like we have Label Tweets "Sheet 1" and "copy of sheet 1." Are we working with copy of sheet 1 to merge the two? If so, I'll dedupe it if you like.

**Comment by edenradovich** [comment]
@frhino sorry just seeing this - "Sheet 1" is the correct sheet. I deleted "copy of sheet1" and have also successfully deduped it. There are now 1455 rows. This means we can also get rid of the "Tweets2" spreadsheet.
