### ISSUE TITLE
Label Tweets 347 - 500

### ISSUE THREAD

**Issue by edenradovich** [sfbrigade/nltweets#26]
https://docs.google.com/spreadsheets/d/1duD-RUOTLNu9zW4aXqfgmow62pOcKUuUitxqeVRkbPs/edit#gid=0

**Comment by frhino** [comment]
@edenradovich did we possibly lose a topic or two when merging these?

**Comment by edenradovich** [comment]
@frhino thanks for pointing that out. Topic #21 wasn't there, but just corrected that now.

**Comment by frhino** [comment]
done
