### ISSUE TITLE
Add geo coords to output data

### ISSUE THREAD

**Issue by frhino** [sfbrigade/nltweets#3]
My beta version just pulls the extended twitter text with no parsing such as @steven4354 link in issue 1. We want to add geo coords to the output so we can aggregate and visualize data according to where tweets were created.

**Comment by VincentLa14** [comment]
@frhino very small nit -- when we refer to an issue, lets also just link it: https://github.com/sfbrigade/nltweets/issues/1 so that it's easier to see what issues refer to what. I think GitHub has some meta stuff too where it says which issues are referred to in other places.

**Comment by frhino** [comment]
Done with issue [45](https://github.com/sfbrigade/nltweets/pull/45)
