### ISSUE TITLE
Research labeling platform

### ISSUE THREAD

**Issue by frhino** [sfbrigade/nltweets#43]
Bob is going to sketch out the effort required for creating a mobile app labeling product for projects to quickly enlist a number of volunteers to label data.

**Comment by frhino** [comment]
@bleeeeee check out [this issue](https://docs.google.com/document/d/1UQCeG7k-Lvl7a72nge-hQXgAv6H8DXTnca-5blFhHuQ/edit) I have with our current method on mobile.

**Comment by bleeeeee** [comment]
So Ariel and Maribel will work on the iOS part and I will look into the Android one.

**Comment by bleeeeee** [comment]
Josh, I see what you mean.  The mobile apps will make this much better.

**Comment by frhino** [comment]
This project is officially incepted and will be organized in its own repo to be opened soon.
