### ISSUE TITLE
Clean twitter output of UTF-8 code

### ISSUE THREAD

**Issue by frhino** [sfbrigade/nltweets#47]
Twitter output contains character encodings rather than punctuation, possibly due to errors of people using the wrong punctuation character when tweeting such as 
```
b'@sfmta_muni how\xe2\x80\x99s this looking for the NX??? a lot of people waiting'
```

**Comment by rileypredum** [comment]
@frhino the notebook I added in my PR uses string.decode('utf-8'). So for the above tweet, it goes from:

b'@sfmta_muni how\xe2\x80\x99s this looking for the NX??? a lot of people waiting'

to

'@sfmta_muni how’s this looking for the NX??? a lot of people waiting'

**Comment by pahdo** [comment]
@rileypredum It looks good to me, I think it's safe to close this issue if you agree.

**Comment by nathanhc** [comment]
can you close it after you write the cleaned text to the file?

**Comment by rileypredum** [comment]
Once PR is approved, I can. It says it has issues, anyone know how to fix it when that happens?
