### ISSUE TITLE
Set up server to log tweets

### ISSUE THREAD

**Issue by frhino** [sfbrigade/nltweets#48]
Probably use AWS lightsail, linux machine to run
https://github.com/mlegy/Slack-logger-bot

**Comment by pahdo** [comment]
How do other projects do Ops/Infrastructure stuff?

**Comment by frhino** [comment]
Open Transit has significant infrastructure on AWS and Google Cloud and pay for it through combination of donated credits and brigade grant

**Comment by pringlized** [comment]
I can help with this.  I'll need some insight into requirements, rough architecture, and budgetary concerns based on the traffic and storage to have a better idea on an MVP to get this off the ground.

Went to my first meeting this week and learning the architecture.  Still learning and have questions whether this should become a live streaming system over time using something like Spark or just be a cron related job. I've built managed a few AWS deployments before but didn't know about Lightsail.  I've used Beanstalk for a PHP deployment.  Did some reading and Lightsail seems like a similar option (not sure the difference yet) if the project needs to run and manage it's own custom instances like having API's that can consume tweets and share data, write to a DB, and possibly using caching for reporting tools. 

I need to noodle this a bit more.  Look forward to any ideas and input.

**Comment by frhino** [comment]
@pringlized 
This can definitely be a cron job, but then with a bot it might be easy to run as an event-triggered job. Let's talk Wed!
@pahdo 
Do you mean in terms of paying for infrastructure? OpenTransit started with credits, then applied for a grant through the brigade.  I'm sure we can get $500 credit from somewhere for Google Cloud or AWS, which should be enough for more than 10 years in terms of server and storage.

**Comment by frhino** [comment]
@pahdo @pringlized Closing this issue as it's duplicated by [issue 78](https://github.com/sfbrigade/nltweets/issues/78).
