### ISSUE TITLE
clean up environments.yml file

### ISSUE THREAD

**Issue by frhino** [sfbrigade/nltweets#49]
The environments.yml file in the root directory causes conflict when I try to implement it:
```
(base) C:\Users\Joshf\Documents\nltweets>conda env create -f environment.yml
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python==3.6.0
  - sqlalchemy==1.1 -> python=2.7
Use "conda info <package>" to see the dependencies for each package.
```
My base environment is python 3.6, so I think that's what's causing the conflict.

**Comment by pahdo** [comment]
I believe @VincentLa closed this issue with https://github.com/sfbrigade/nltweets/pull/57
