### ISSUE TITLE
Update README and Onboarding Documentation

### ISSUE THREAD

**Issue by VincentLa14** [sfbrigade/nltweets#5]
Update the root README file, especially the [Overview](https://github.com/sfbrigade/nltweets#overview) section and the [Needs of the Project](https://github.com/sfbrigade/nltweets#overview). This will make it easier to onboard new members and know what we need to pitch for.

**Comment by frhino** [comment]
move trailing readme content to wiki

**Comment by frhino** [comment]
Breaking this issue down into separate issues. Onboarding is fairly complete in the [wiki](https://github.com/sfbrigade/nltweets/wiki)
