### ISSUE TITLE
Add twitter data cleaning step prior to labeling

### ISSUE THREAD

**Issue by frhino** [sfbrigade/nltweets#50]
Occasionally people will spam @sfmta_muni with more than 2 tweets in a short amount of time (e.g. < 30 minutes). We should purge all but the first, or better, merge them all via concatenation so the two possible topics must be pulled from the entirety of the diatribe rather than scoring multiple hits for the same issue.

**Comment by frhino** [comment]
We'll need usernames for the tweeters, as in [issue 37](https://github.com/sfbrigade/nltweets/issues/37).

**Comment by pahdo** [comment]
@rileypredum Did your merged PR address this issue? If so, we can close this

**Comment by rileypredum** [comment]
No, it did basic NLP library cleaning like removing stop words and punctuation and such.

**Comment by frhino** [comment]
What I had in mind when I created this issue is to add whatever processing
we needed to have a clean flat file prior to the nlp stuff, e.g the "b"s
gone and the fields cleanly delimited.

**Comment by rileypredum** [comment]
https://github.com/sfbrigade/nltweets/issues/47#issuecomment-468128090 @frhino Does this work?

**Comment by rileypredum** [comment]
I removed the NLP cleaning steps and am focusing on just the decoding. Anyone know how to clean emojis though?

**Comment by rileypredum** [comment]
My PR is pending, once approved, this has been resolved
