### ISSUE TITLE
Standardize Development Environment

### ISSUE THREAD

**Issue by VincentLa14** [sfbrigade/nltweets#6]
In other Data Science Working Group projects, I've used Anaconda to manage Python Environments. I'm open to continue doing this or other solutions (e.g. Docker image), but we should have some way to standardize Development Environment to facilitate onboarding. 

Very basic MVP could even just be a list of steps to do manually. We should then document this in our Onboarding Docs. My proposal would be to create a folder called "onboarding" within the root directory with different Markdown pages within that directory.

For example, the Data Science Working Group Small Business Administration Project had this: https://github.com/sfbrigade/datasci-sba/tree/master/onboarding

**Comment by frhino** [comment]
Nick would you mind writing up a small blurb on the Readme for how to work with the requirements file? Lots of people getting started with python wind up with python downloaded from pthon.org as well as anaconda environments and maybe some other flavor. It would be cool if we could say, "if you have installed python from download at python.org, do this. But if you have python installed via Anaconda, do that."

**Comment by frhino** [comment]
Vincent that collection of onboarding docs you linked to is amazing. OpenTransit will definitely be wholesale stealing that. I think you, Nick, and Daniel should all sign off on whatever environment management approach you think is the most usable, intuitive, common, etc. I can be the litmus test on whether it's adequately documented for let's say  "less technical" people.
