### ISSUE TITLE
Add dummy example of creds.txt

### ISSUE THREAD

**Issue by frhino** [sfbrigade/nltweets#63]
I'm getting 
```
'{"errors":[{"code":89,"message":"Invalid or expired token."}]}'
```
in the CodeLabs example [CodeLab0TwitterAPI.ipynb](https://github.com/sfbrigade/nltweets/blob/master/codelabs/CodeLab0TwitterAPI.ipynb). Can we include an example of the structure like the following dummy values, "Your creds.txt file will look like this:
```
ACCESS_KEY.123456789876543210
ACCESS_SECRET.abCD123E4f6ghi7jkLmnOPqR89sTUv8WXYZy7Xw6vUtsr
CONSUMER_KEY.1ABC2defG3HI4JkLmNOpQrs5T
CONSUMER_SECRET.abCD123E4f6ghi7jkLmnOPqR89sTUv8WXYZy7Xw6vUtsr5qp4o
```
But not that, because that throws an error.

**Comment by pahdo** [comment]
Ah I see how the directions are a bit confusing. Let me upload an example

**Comment by pahdo** [comment]
Closed by https://github.com/sfbrigade/nltweets/pull/67
