### ISSUE TITLE
Can we search twitter for unlimited size list of tweet ID?

### ISSUE THREAD

**Issue by frhino** [sfbrigade/nltweets#79]
As we implement regular pulling of twitter data, if we save them by tweet ID, can we use our existing API creds (free tier) to re-pull the full tweets of all our tweet IDs? This would allow us to compare new classifier models with older ones. If we accumulate 1 million tweet IDs, can we request a batch from the first 100K?

**Comment by pahdo** [comment]
Hmm.. my intuition tells me no. Are there restrictions preventing us from archiving all the tweets ourselves?

**Comment by frhino** [comment]
https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-show-id.html

According to this, we can request up to 100 tweets at a time by tweet ID. Plus, the standard (free) API is restricted to last 7 days and draws from a random subset, not all tweets. Doesn't sound like that's good enough. I like your idea of hashing usernames.

**Comment by frhino** [comment]
So, closing this. Let's talk about hashing usernames in another issue.
